import type React from "react";

export const ModelCard: React.FC = () => (
  <div className="page-wrap">
    <h1 className="page-title">Model Card</h1>
    <p className="page-sub">Transparency documentation for the DeepScan CNN+LSTM deepfake detector.</p>

    {/* Model Details */}
    <section className="mc-section">
      <h2 className="mc-heading">Model Details</h2>
      <table className="mc-table">
        <tbody>
          <tr><th scope="row">Model name</th><td>DeepScan CNN+LSTM</td></tr>
          <tr><th scope="row">Version</th><td>1.0 (MLflow registry)</td></tr>
          <tr><th scope="row">Input</th><td>MP4 video, up to 100 MB</td></tr>
          <tr><th scope="row">Output</th><td>real / fake + confidence score (0–100%)</td></tr>
          <tr><th scope="row">Inference latency</th><td>P95 &lt; 200 ms (CPU)</td></tr>
          <tr><th scope="row">Explainability</th><td>Grad-CAM saliency map per prediction</td></tr>
        </tbody>
      </table>
    </section>

    {/* Architecture */}
    <section className="mc-section">
      <h2 className="mc-heading">Architecture</h2>
      <p className="mc-text">
        The model uses a two-stage pipeline. <strong>EfficientNet-B0</strong> (pretrained on ImageNet)
        extracts a 1280-dimensional feature vector from each sampled frame. A single-layer
        <strong> LSTM</strong> (hidden size 256) then processes the sequence of frame features to capture
        temporal manipulation artifacts. A final linear layer produces a scalar probability in [0, 1];
        values ≥ 0.5 are classified as <em>fake</em>.
      </p>
    </section>

    {/* Training Data */}
    <section className="mc-section">
      <h2 className="mc-heading">Training Data</h2>
      <p className="mc-text">
        Trained on the <strong>SDFVD (Synthetic Deepfake Video Dataset)</strong>. The dataset contains
        an equal split of authentic and AI-generated videos. Face detection (MTCNN) is applied to
        each frame before feature extraction. Training used an 80/10/10 train/val/test split.
      </p>
    </section>

    {/* Intended Use */}
    <section className="mc-section">
      <h2 className="mc-heading">Intended Use</h2>
      <p className="mc-text">
        DeepScan is designed for research and demonstration purposes — to illustrate how a deepfake
        detector can be built, deployed, and monitored end-to-end using MLOps practices. It is
        <strong> not</strong> intended for high-stakes production decisions without human review.
      </p>
    </section>

    {/* Limitations */}
    <section className="mc-section">
      <h2 className="mc-heading">Limitations</h2>
      <ul className="mc-list">
        <li>Performance may degrade on deepfakes generated by unseen techniques not in training data.</li>
        <li>Videos without detectable faces fall back to a center-crop — confidence may be lower.</li>
        <li>Model is CPU-only in the current deployment; inference may be slower on long videos.</li>
        <li>Confidence near 50% indicates ambiguous content — treat results with caution.</li>
      </ul>
    </section>

    {/* Evaluation Metrics */}
    <section className="mc-section">
      <h2 className="mc-heading">Evaluation Metrics</h2>
      <table className="mc-table">
        <tbody>
          <tr><th scope="row">Val Accuracy</th><td>100% (MLflow run 0215feaa)</td></tr>
          <tr><th scope="row">Val F1-score</th><td>1.0</td></tr>
          <tr><th scope="row">Best epoch</th><td>11</td></tr>
          <tr><th scope="row">P95 latency</th><td>&lt; 200 ms</td></tr>
        </tbody>
      </table>
    </section>

    {/* Responsible AI */}
    <section className="mc-section mc-notice">
      <h2 className="mc-heading">Responsible AI Notice</h2>
      <p className="mc-text">
        Deepfake detection is an adversarial problem — attackers can adapt to evade any detector.
        Results should always be treated as probabilistic indicators, not ground truth.
        Incorrect predictions (false positives and false negatives) are expected.
        Always apply human judgement and do not make consequential decisions based solely on this tool.
      </p>
    </section>
  </div>
);
